[package]
name = "xtensis-tui"
version = "0.1.0"
description = "Prototype of a TUI for xtensis"
license = "MIT OR Apache2.0"
homepage = "https://github.com/shymega/xtensis-tui"
repository = "https://github.com/shymega/xtensis-tui.git"
keywords = ["editor", "framework", "text"]
readme = "README.md"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]

[lib]
name = "xtensistui"
path = "src/lib.rs"

[[bin]]
name = "xtensis-tui"
path = "src/bin/xtensis-tui.rs"

[features]
default=[]

[dependencies]
log = "0.3.6"
fern = "0.3.5"
time = "0.1.35"
serde = "0.8.1"
serde_json = "0.8.1"
docopt = "0.6.82"
rustc-serialize = "0.3"

[dependencies.rustbox]
git = "https://github.com/gchp/rustbox"
